/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.udc.fic.medregatas.view.dialogs;

import es.udc.fic.medregatas.model.regata.Regata;
import es.udc.fic.medregatas.model.service.RegataService;
import es.udc.fic.medregatas.util.exceptions.DuplicateInstanceException;
import es.udc.fic.medregatas.util.exceptions.EmptyTextException;
import es.udc.fic.medregatas.view.MainAppjFrame;
import java.awt.Component;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author iago
 */
public class RegistrarDatosRegataJDialog extends javax.swing.JDialog {

    private MainAppjFrame parent;
    private RegataService regataService;
    private Component frame;
    private Regata regata;

    /**
     * Creates new form RegistrarDatosRegataJDialog
     */
    public RegistrarDatosRegataJDialog(MainAppjFrame parent, Regata regata) {
        super(parent, true);
        initComponents();

        this.parent = parent;
        this.regata = regata;
        this.regataService = parent.getAppContext().getBean(RegataService.class);

        if (regata != null) {
            nombrejTextField.setText(regata.getNombre());
            descripcionjTextArea.setText(regata.getDescripcion());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombrejTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcionjTextArea = new javax.swing.JTextArea();
        continuarjButton = new javax.swing.JButton();
        cancelarjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Crear Regata");

        jLabel1.setText("Nombre");

        jLabel2.setText("Descripción");

        descripcionjTextArea.setColumns(20);
        descripcionjTextArea.setRows(5);
        jScrollPane1.setViewportView(descripcionjTextArea);

        continuarjButton.setText("Siguiente");
        continuarjButton.setToolTipText("");
        continuarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarjButtonActionPerformed(evt);
            }
        });

        cancelarjButton.setText("Cancelar");
        cancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombrejTextField)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancelarjButton)
                        .addGap(18, 18, 18)
                        .addComponent(continuarjButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombrejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continuarjButton)
                    .addComponent(cancelarjButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void continuarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarjButtonActionPerformed

        String nombreRegata = nombrejTextField.getText();
        List<Regata> regatas = regataService.getRegatas();

        try {
            if (nombreRegata.isEmpty()) {
                throw new EmptyTextException(nombreRegata);
            }

            //Si no la estamos editando hacemos la comprobación simple
            if (regata != null && regata.getIdRegata() != null) {
                // Si la estamos editando evitamos compararla con su propio nombre
                for (Regata r : regatas) {
                    if ((!regata.getIdRegata().equals(r.getIdRegata()))
                            && (r.getNombre().equalsIgnoreCase(nombreRegata))) {
                        throw new DuplicateInstanceException(evt, nombreRegata);
                    }
                }
            } else {
                for (Regata r : regatas) {
                    if (r.getNombre().equalsIgnoreCase(nombreRegata)) {
                        throw new DuplicateInstanceException(evt, nombreRegata);
                    }
                }
            }
            //Si no la estamos editando la creamos, en otro caso la editamos
            if (regata == null) {
                regata = new Regata(nombreRegata,
                        descripcionjTextArea.getText());
            } else {
                regata.setNombre(nombreRegata);
                regata.setDescripcion(descripcionjTextArea.getText());
            }

            setVisible(false);
            dispose();

            JDialog dialog = new RegistrarTiposRegataJDialog(parent, regata, null);
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);

        } catch (EmptyTextException e) {
            JOptionPane.showMessageDialog(frame,
                    "El nombre de la regata no puede estar vacía",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } catch (DuplicateInstanceException e) {
            JOptionPane.showMessageDialog(frame,
                    "El nombre de la regata ya existe",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_continuarjButtonActionPerformed

    private void cancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjButtonActionPerformed
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancelarjButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JButton continuarjButton;
    private javax.swing.JTextArea descripcionjTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombrejTextField;
    // End of variables declaration//GEN-END:variables
}
