/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.udc.fic.medregatas.view.panels;

import es.udc.fic.medregatas.view.dialogs.RegistrarMangaJDialog;
import es.udc.fic.medregatas.model.barco.Barco;
import es.udc.fic.medregatas.model.inscripcion.Inscripcion;
import es.udc.fic.medregatas.model.manga.Manga;
import es.udc.fic.medregatas.model.posicion.Posicion;
import es.udc.fic.medregatas.model.regata.Regata;
import es.udc.fic.medregatas.model.service.InscripcionService;
import es.udc.fic.medregatas.model.service.MangaService;
import es.udc.fic.medregatas.model.service.RegataService;
import es.udc.fic.medregatas.model.tipo.Tipo;
import es.udc.fic.medregatas.view.MainAppjFrame;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author samuel,iago,jesus,adrian,diego
 */
public class MostratMangasJPanel extends javax.swing.JPanel {

    private MainAppjFrame parent;

    private InscripcionService inscService;

    private MangaService mangaService;
    private RegataService regataService;

    private Regata regata;
    private List<Manga> mangas;
    private DefaultTableModel mangasModel;
    private DefaultTableModel barcosModel;

    /**
     * Creates new form NewJPanel
     */
    public MostratMangasJPanel(MainAppjFrame parent) {

        initComponents();

        this.parent = parent;
        inscService = parent.getAppContext().getBean(InscripcionService.class);
        mangaService = parent.getAppContext().getBean(MangaService.class);
        regataService = parent.getAppContext().getBean(RegataService.class);

        this.regata = parent.getSelectedRegata();
        this.mangas = mangaService.findByRegata(regata);
        mangasModel = (DefaultTableModel) jTable1.getModel();
        barcosModel = (DefaultTableModel) jTable2.getModel();
        jTable1.setModel(rellenarMangas());
        jTable2.setModel(rellenarTablaResultados());
    }

    private DefaultTableModel rellenarMangas() {

        mangasModel.setRowCount(0);

        for (Manga m : mangas) {
            Object[] o = {m.getIdManga(), m.getMillas()};
            mangasModel.addRow(o);
        }

        return mangasModel;
    }

    /**
     * Inserta todas las posiciones registradas para esa manga, ordenadas por
     * tipo y dentro de cada tipo por puntuación.
     *
     * @return
     */
    private DefaultTableModel rellenarTablaResultados() {

        if (jTable1.getSelectedRow() != -1) {

            barcosModel.setRowCount(0);
            Map<Barco, String> patrones = new HashMap<Barco, String>();
            Manga manga = mangas.get(jTable1.getSelectedRow());

            //Guardamos la información de los patrones
            for (Inscripcion i : inscService.getInscripciones(regata)) {
                patrones.put(i.getBarco(), i.getPatron());
            }


            for (Tipo tipo : regataService.getTiposAsociadosByRegata(regata)) {
                // Para cada uno de los tipos participantes en la regata añadimos
                // sus barcos a la lista.
                for (Posicion p : regataService.getClasificacionManga(manga, tipo)) {
                    Object[] o = {p.getBarco(),
                        patrones.get(p.getBarco()),
                        tipo.getNombre(),
                        p.getPuntos()};
                    barcosModel.addRow(o);
                }
            }
        }
        return barcosModel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        CreateMangaButton = new javax.swing.JButton();
        jBorrarManga = new javax.swing.JButton();
        jEditManga = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Manga", "Millas"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num. Vela", "Patrón", "Clase", "Puntos"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable2);

        CreateMangaButton.setText("Crear Manga");
        CreateMangaButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateMangaButtonMouseClicked(evt);
            }
        });

        jBorrarManga.setText("Borrar Manga");
        jBorrarManga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBorrarMangaMouseClicked(evt);
            }
        });
        jBorrarManga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBorrarMangaActionPerformed(evt);
            }
        });

        jEditManga.setText("Editar Manga");
        jEditManga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEditMangaActionPerformed(evt);
            }
        });

        jLabel1.setText("Mangas");

        jLabel2.setText("Resultado:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBorrarManga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jEditManga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CreateMangaButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(171, 171, 171)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBorrarManga)
                    .addComponent(CreateMangaButton)
                    .addComponent(jEditManga))
                .addContainerGap(20, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CreateMangaButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateMangaButtonMouseClicked
        // TODO add your handling code here:
        JDialog dialog = new RegistrarMangaJDialog(parent, true, null);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        jTable1.setModel(rellenarMangas());
    }//GEN-LAST:event_CreateMangaButtonMouseClicked

    private void jBorrarMangaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBorrarMangaMouseClicked
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() == -1) {
            return;
        }

        List<Manga> mangasAct = mangaService.findByRegata(regata);
        Manga mangaABorrar = mangasAct.get(jTable1.getSelectedRow());

        mangaService.borrarManga(mangaABorrar);

        parent.refresh(PanelEnum.PANNEL_MANGAS);

    }//GEN-LAST:event_jBorrarMangaMouseClicked

    private void jEditMangaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEditMangaActionPerformed
        // TODO add your handling code here:
        if (jTable1.getSelectedRow() == -1) {
            return;
        }

        List<Manga> mangasAct = mangas;
        Manga mangaAEditar = mangasAct.get(jTable1.getSelectedRow());

        JDialog dialog = new RegistrarMangaJDialog(parent, true, mangaAEditar);
        dialog.setTitle("Editar Manga");
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
        jTable1.setModel(rellenarMangas());

        //Recuperar las millas de la manga y ponerlas como default en el edit
        //recuperar la tabla de barcos inscritos y añadirlos a la tabla de edit
    }//GEN-LAST:event_jEditMangaActionPerformed

    private void jBorrarMangaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBorrarMangaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBorrarMangaActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        jTable2.setModel(rellenarTablaResultados());
    }//GEN-LAST:event_jTable1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateMangaButton;
    private javax.swing.JButton jBorrarManga;
    private javax.swing.JButton jEditManga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
