/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package es.udc.fic.medregatas.view.panels;

import es.udc.fic.medregatas.model.barco.Barco;
import es.udc.fic.medregatas.model.service.InscripcionService;
import es.udc.fic.medregatas.model.service.RegataService;
import es.udc.fic.medregatas.model.tipo.Tipo;
import es.udc.fic.medregatas.util.exceptions.TipoAlreadyUsedException;
import es.udc.fic.medregatas.view.MainAppjFrame;
import es.udc.fic.medregatas.view.dialogs.NuevoTipoJDialog;
import java.awt.Component;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JOptionPane;

/**
 *
 * @author Abosan
 */
public class MostrarTiposJPanel extends javax.swing.JPanel {

    private MainAppjFrame parent;

    private RegataService regataService;

    private InscripcionService inscripcionService;

    private Tipo tipoSelecc;
    private Component frame;

    /**
     * Creates new form MostrarTipos
     *
     * @param parent
     */
    public MostrarTiposJPanel(MainAppjFrame parent) {
        initComponents();
        this.parent = parent;
        regataService = parent.getAppContext().getBean(RegataService.class);
        inscripcionService = parent.getAppContext().getBean(InscripcionService.class);
        tiposList.setListData(regataService.getTipos().toArray());
        contenidoCTRLabel.setText(" ");
        contenidoNombreLabel.setText(" ");
    }

    public void loadTabs() {

        descTextArea.setText(tipoSelecc.getDescripcion());
        if (tipoSelecc.getCompiteTmpReal()) {
            contenidoCTRLabel.setText(" Si ");
        } else {
            contenidoCTRLabel.setText(" No ");
        }
        contenidoNombreLabel.setText(tipoSelecc.getNombre());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tiposList = new javax.swing.JList();
        nombreListLabel = new javax.swing.JLabel();
        claseJLabel = new javax.swing.JLabel();
        descripcionJLabel = new javax.swing.JLabel();
        compiteTRJLabel = new javax.swing.JLabel();
        eliminarButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        anhadirButton = new javax.swing.JButton();
        contenidoNombreLabel = new javax.swing.JLabel();
        contenidoCTRLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        descTextArea = new javax.swing.JTextArea();

        tiposList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        tiposList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tiposListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tiposList);

        nombreListLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        nombreListLabel.setText("Todas las clases");

        claseJLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        claseJLabel.setText("Clase:");

        descripcionJLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        descripcionJLabel.setText("Descripción:");

        compiteTRJLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        compiteTRJLabel.setText("Compite en Tiempo Real:");

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        editarButton.setText("Editar");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        anhadirButton.setText("Añadir");
        anhadirButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                anhadirButtonMouseClicked(evt);
            }
        });

        contenidoNombreLabel.setText("ejemplo de clase");

        contenidoCTRLabel.setText("ejemplo de CTR");

        descTextArea.setEditable(false);
        descTextArea.setColumns(20);
        descTextArea.setLineWrap(true);
        descTextArea.setRows(5);
        descTextArea.setWrapStyleWord(true);
        descTextArea.setAutoscrolls(false);
        descTextArea.setBorder(null);
        descTextArea.setCursor(null);
        descTextArea.setFocusable(false);
        descTextArea.setOpaque(false);
        jScrollPane2.setViewportView(descTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(anhadirButton)
                                .addGap(18, 18, 18)
                                .addComponent(editarButton)
                                .addGap(18, 18, 18)
                                .addComponent(eliminarButton))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(compiteTRJLabel)
                                            .addComponent(claseJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(descripcionJLabel)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(contenidoNombreLabel)
                                                    .addComponent(contenidoCTRLabel))))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addComponent(nombreListLabel))
                .addGap(11, 11, 11))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(nombreListLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(claseJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contenidoNombreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descripcionJLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(compiteTRJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(contenidoCTRLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eliminarButton)
                            .addComponent(editarButton)
                            .addComponent(anhadirButton)))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void anhadirButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anhadirButtonMouseClicked
        JDialog dialog = new NuevoTipoJDialog(parent, true, null);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);

    }//GEN-LAST:event_anhadirButtonMouseClicked

    private void tiposListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tiposListMouseClicked

        tipoSelecc = (Tipo) tiposList.getSelectedValue();
        loadTabs();

    }//GEN-LAST:event_tiposListMouseClicked

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        tipoSelecc = (Tipo) tiposList.getSelectedValue();
        JDialog dialog = new NuevoTipoJDialog(parent, true, tipoSelecc);
        dialog.setLocationRelativeTo(null);
        dialog.setVisible(true);
    }//GEN-LAST:event_editarButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        try {
            tipoSelecc = (Tipo) tiposList.getSelectedValue();
            List<Barco> barcos = inscripcionService.findAllBarcos();
            for (Barco b : barcos) {
                if (b.getTipo().getNombre().equalsIgnoreCase(tipoSelecc.getNombre())) {
                    throw new TipoAlreadyUsedException(tipoSelecc);
                }
            }

            regataService.removeTipo(tipoSelecc.getIdTipo());
            JOptionPane.showMessageDialog(frame,
                    "Clase " + tipoSelecc.getNombre() + " ha sido eliminada satisfactoriamente",
                    "Borrado",
                    JOptionPane.INFORMATION_MESSAGE);
            parent.refresh(PanelEnum.PANNEL_CLASES);

        } catch (TipoAlreadyUsedException e) {
            JOptionPane.showMessageDialog(frame,
                    "Imposible eliminar: Algún barco registrado ya pertenece a esta clase",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_eliminarButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anhadirButton;
    private javax.swing.JLabel claseJLabel;
    private javax.swing.JLabel compiteTRJLabel;
    private javax.swing.JLabel contenidoCTRLabel;
    private javax.swing.JLabel contenidoNombreLabel;
    private javax.swing.JTextArea descTextArea;
    private javax.swing.JLabel descripcionJLabel;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel nombreListLabel;
    private javax.swing.JList tiposList;
    // End of variables declaration//GEN-END:variables
}
